#!/usr/bin/env python3
"""Generate a preview dashboard with sample data — no API keys needed."""

import db
import dashboard
from datetime import datetime, timedelta
import random

SAMPLE_DEALS = [
    {
        "company_name": "Synthara AI",
        "amount_usd": 45000000,
        "amount_raw": "$45M",
        "currency": "USD",
        "round_type": "Series B",
        "lead_investors": ["Sequoia Capital", "Accel"],
        "other_investors": ["Y Combinator", "SV Angel"],
        "company_hq_country": "United States",
        "company_hq_city": "San Francisco",
        "sector": "AI/ML",
        "short_description": "AI-powered drug discovery platform for pharmaceutical companies.",
        "valuation": "$300M",
        "source_urls": ["https://example.com/synthara"],
        "source_names": ["TechCrunch"],
    },
    {
        "company_name": "GreenVolt Energy",
        "amount_usd": 27000000,
        "amount_raw": "€25M",
        "currency": "EUR",
        "round_type": "Series A",
        "lead_investors": ["Northzone"],
        "other_investors": ["EQT Ventures", "Cherry Ventures"],
        "company_hq_country": "Germany",
        "company_hq_city": "Berlin",
        "sector": "CleanTech",
        "short_description": "Smart grid optimization for renewable energy storage.",
        "valuation": None,
        "source_urls": ["https://example.com/greenvolt"],
        "source_names": ["Sifted"],
    },
    {
        "company_name": "PayFlow",
        "amount_usd": 120000000,
        "amount_raw": "$120M",
        "currency": "USD",
        "round_type": "Series C",
        "lead_investors": ["Andreessen Horowitz"],
        "other_investors": ["Tiger Global", "Ribbit Capital"],
        "company_hq_country": "United States",
        "company_hq_city": "New York",
        "sector": "FinTech",
        "short_description": "B2B payment infrastructure for cross-border transactions.",
        "valuation": "$1.2B",
        "source_urls": ["https://example.com/payflow"],
        "source_names": ["TechCrunch"],
    },
    {
        "company_name": "MediScan",
        "amount_usd": 8500000,
        "amount_raw": "£6.7M",
        "currency": "GBP",
        "round_type": "Seed",
        "lead_investors": ["Balderton Capital"],
        "other_investors": ["LocalGlobe"],
        "company_hq_country": "United Kingdom",
        "company_hq_city": "London",
        "sector": "HealthTech",
        "short_description": "AI diagnostic imaging tool for early cancer detection.",
        "valuation": None,
        "source_urls": ["https://example.com/mediscan"],
        "source_names": ["Sifted"],
    },
    {
        "company_name": "BuildOS",
        "amount_usd": 18000000,
        "amount_raw": "$18M",
        "currency": "USD",
        "round_type": "Series A",
        "lead_investors": ["a16z"],
        "other_investors": ["Founders Fund"],
        "company_hq_country": "United States",
        "company_hq_city": "Austin",
        "sector": "PropTech",
        "short_description": "Construction project management platform with AI scheduling.",
        "valuation": None,
        "source_urls": ["https://example.com/buildos"],
        "source_names": ["VentureBeat"],
    },
    {
        "company_name": "DataMesh",
        "amount_usd": 55000000,
        "amount_raw": "$55M",
        "currency": "USD",
        "round_type": "Series B",
        "lead_investors": ["Lightspeed Venture Partners"],
        "other_investors": ["GV", "Greylock Partners"],
        "company_hq_country": "United States",
        "company_hq_city": "Seattle",
        "sector": "SaaS",
        "short_description": "Real-time data pipeline platform for enterprise analytics.",
        "valuation": "$400M",
        "source_urls": ["https://example.com/datamesh"],
        "source_names": ["TechCrunch"],
    },
    {
        "company_name": "Logistiq",
        "amount_usd": 32400000,
        "amount_raw": "€30M",
        "currency": "EUR",
        "round_type": "Series B",
        "lead_investors": ["Index Ventures"],
        "other_investors": ["Atomico", "Creandum"],
        "company_hq_country": "Netherlands",
        "company_hq_city": "Amsterdam",
        "sector": "Logistics",
        "short_description": "Last-mile delivery optimization for European e-commerce.",
        "valuation": None,
        "source_urls": ["https://example.com/logistiq"],
        "source_names": ["EU-Startups"],
    },
    {
        "company_name": "CyberShield",
        "amount_usd": 70000000,
        "amount_raw": "$70M",
        "currency": "USD",
        "round_type": "Series C",
        "lead_investors": ["Insight Partners"],
        "other_investors": ["CrowdStrike Falcon Fund", "Sequoia Capital"],
        "company_hq_country": "Israel",
        "company_hq_city": "Tel Aviv",
        "sector": "Cybersecurity",
        "short_description": "Zero-trust network security for distributed workforces.",
        "valuation": "$500M",
        "source_urls": ["https://example.com/cybershield"],
        "source_names": ["VentureBeat"],
    },
    {
        "company_name": "NutriGenome",
        "amount_usd": 3200000,
        "amount_raw": "$3.2M",
        "currency": "USD",
        "round_type": "Pre-Seed",
        "lead_investors": ["Techstars"],
        "other_investors": [],
        "company_hq_country": "United States",
        "company_hq_city": "Boston",
        "sector": "HealthTech",
        "short_description": "Personalized nutrition plans based on genomic data.",
        "valuation": None,
        "source_urls": ["https://example.com/nutrigenome"],
        "source_names": ["NewsAPI"],
    },
    {
        "company_name": "FleetZero",
        "amount_usd": 15000000,
        "amount_raw": "€13.9M",
        "currency": "EUR",
        "round_type": "Series A",
        "lead_investors": ["EQT Ventures"],
        "other_investors": ["Lakestar", "HV Capital"],
        "company_hq_country": "Sweden",
        "company_hq_city": "Stockholm",
        "sector": "CleanTech",
        "short_description": "Electric fleet management and charging infrastructure for logistics.",
        "valuation": None,
        "source_urls": ["https://example.com/fleetzero"],
        "source_names": ["Tech.eu"],
    },
    {
        "company_name": "LegalPad AI",
        "amount_usd": 22000000,
        "amount_raw": "$22M",
        "currency": "USD",
        "round_type": "Series A",
        "lead_investors": ["Benchmark"],
        "other_investors": ["First Round Capital"],
        "company_hq_country": "United States",
        "company_hq_city": "San Francisco",
        "sector": "LegalTech",
        "short_description": "AI contract review and negotiation assistant for law firms.",
        "valuation": None,
        "source_urls": ["https://example.com/legalpad"],
        "source_names": ["TechCrunch"],
    },
    {
        "company_name": "AgroSense",
        "amount_usd": 10800000,
        "amount_raw": "€10M",
        "currency": "EUR",
        "round_type": "Seed",
        "lead_investors": ["Partech"],
        "other_investors": ["Serena Capital"],
        "company_hq_country": "France",
        "company_hq_city": "Paris",
        "sector": "AgriTech",
        "short_description": "Satellite-powered crop monitoring and yield prediction.",
        "valuation": None,
        "source_urls": ["https://example.com/agrosense"],
        "source_names": ["EU-Startups"],
    },
    {
        "company_name": "QuantumLeap Computing",
        "amount_usd": 200000000,
        "amount_raw": "$200M",
        "currency": "USD",
        "round_type": "Series D+",
        "lead_investors": ["SoftBank Vision Fund"],
        "other_investors": ["Google Ventures", "IQT"],
        "company_hq_country": "United States",
        "company_hq_city": "Chicago",
        "sector": "DeepTech",
        "short_description": "Quantum computing-as-a-service platform for enterprise R&D.",
        "valuation": "$2B",
        "source_urls": ["https://example.com/quantumleap"],
        "source_names": ["VentureBeat"],
    },
    {
        "company_name": "WellNest",
        "amount_usd": 6000000,
        "amount_raw": "$6M",
        "currency": "USD",
        "round_type": "Seed",
        "lead_investors": ["Bessemer Venture Partners"],
        "other_investors": [],
        "company_hq_country": "United States",
        "company_hq_city": "Los Angeles",
        "sector": "HealthTech",
        "short_description": "Mental health platform connecting employees with licensed therapists.",
        "valuation": None,
        "source_urls": ["https://example.com/wellnest"],
        "source_names": ["NewsAPI"],
    },
    {
        "company_name": "TradeBridge",
        "amount_usd": 38000000,
        "amount_raw": "£30M",
        "currency": "GBP",
        "round_type": "Series B",
        "lead_investors": ["Balderton Capital", "Draper Esprit"],
        "other_investors": ["Goldman Sachs"],
        "company_hq_country": "United Kingdom",
        "company_hq_city": "London",
        "sector": "FinTech",
        "short_description": "Trade finance platform digitizing supply chain payments.",
        "valuation": "$250M",
        "source_urls": ["https://example.com/tradebridge"],
        "source_names": ["Sifted"],
    },
]


def main():
    db.init_db()

    now = datetime.utcnow()
    for i, deal in enumerate(SAMPLE_DEALS):
        # Spread deals across the last 7 days, with most today
        days_ago = min(i // 3, 6)
        deal["published_date"] = (now - timedelta(days=days_ago)).strftime("%Y-%m-%dT%H:%M:%SZ")
        db.insert_deal(deal)

    print(f"Inserted {len(SAMPLE_DEALS)} sample deals.")
    dashboard.render_dashboard()
    print("Preview dashboard generated at output/index.html")


if __name__ == "__main__":
    main()
